dist: trusty
language: ruby
sudo: false
rvm:
- 2.5.0
env:
  global:
  - DATABASE_URL=postgres://postgres@localhost:5432/test
  - REDIS_URL=redis://localhost:637
  - RUBY_ENV=test
  - RACK_ENV=test
  - RAILS_ENV=test
  - SECRET_KEY_BASE=secret_key
  matrix:
  - DB=postgresql

before_install:
- gem install bundler -v 1.16.1

cache:
  bundler: true
  directories:
    - /home/travis/.rvm

before_script:
- bundle install
- make db-travis

services:
- postgresql

addons:
  postgresql: '9.5'

notifications:
    email: false
