dist: trusty
language: ruby
sudo: false
rvm:
- 2.5.0
env:
  global:
  - DATABASE_URL=postgres://postgres@localhost:5432/test
  - REDIS_URL=redis://localhost:637
  - RUBY_ENV=test
  - RACK_ENV=test
  - RAILS_ENV=test
  - SECRET_KEY_BASE=secret_key
  - CC_TEST_REPORTER_ID=805ff98174fa20abbb55160dfae98785800e169da6ca3e6c3335a193e577879a
  - HOST_NAME=rmst-test.travic-ci.org
  - API_KEY_SENDWITHUS=travis
  matrix:
  - DB=postgresql

before_install:
- gem install bundler -v 1.16.1

cache:
  bundler: true
  directories:
    - /home/travis/.rvm

before_script:
- bundle install
- make db-travis
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
- postgresql

addons:
  postgresql: '9.5'

notifications:
    email: false
